name: Build and Push Images to Amazon ECR

on:
  push:
    branches: [ "main" ]

env:
  AWS_REGION: us-east-1
  ECR_WEBAPP_REPO: clo835-a1-webapp
  ECR_MYSQL_REPO: clo835-a1-mysql

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push Webapp image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_WEBAPP_REPO:$IMAGE_TAG -f Dockerfile .
          docker push $ECR_REGISTRY/$ECR_WEBAPP_REPO:$IMAGE_TAG
          docker tag  $ECR_REGISTRY/$ECR_WEBAPP_REPO:$IMAGE_TAG $ECR_REGISTRY/$ECR_WEBAPP_REPO:latest
          docker push $ECR_REGISTRY/$ECR_WEBAPP_REPO:latest

      - name: Build and push MySQL image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_MYSQL_REPO:$IMAGE_TAG -f Dockerfile_mysql .
          docker push $ECR_REGISTRY/$ECR_MYSQL_REPO:$IMAGE_TAG
          docker tag  $ECR_REGISTRY/$ECR_MYSQL_REPO:$IMAGE_TAG $ECR_REGISTRY/$ECR_MYSQL_REPO:latest
          docker push $ECR_REGISTRY/$ECR_MYSQL_REPO:latest
